# Copyright (c) 2020 makerdiary.com

# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:

# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.

# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

# Project information
site_name: nRF52840 M.2 Developer Kit
site_description: The documentation offers all you need to start developing with nRF52840 M.2 Developer Kit.
site_author: makerdiary
site_url: https://wiki.makerdiary.com/nrf52840-m2-devkit/

# Repository
repo_name: makerdiary/nrf52840-m2-devkit
repo_url: https://github.com/makerdiary/nrf52840-m2-devkit
edit_uri: ""

# Copyright
copyright: 'Copyright &copy; 2020 <a href="https://wiki.makerdiary.com" target="_blank">wiki.makerdiary.com</a>'

# Configuration
theme:
  name: null
  custom_dir: 'mkdocs-material/material'

  # 404 page
  static_templates:
    - 404.html

  # Don't include MkDocs' JavaScript
  include_search_page: false
  search_index_only: true

  # Default values, taken from mkdocs_theme.yml
  language: en
  feature:
    tabs: true
  palette:
    primary: red-bud
    accent: red-bud
  font:
    text: Roboto
    code: Roboto Mono
  favicon: 'assets/images/favicon.png'
  logo: 'assets/images/logo.svg'

# Plugins
plugins:
  - search
  - minify:
      minify_html: true

# Customization
extra:
  social:
    - type: comments
      link: https://community.makerdiary.com
    - type: globe
      link: https://makerdiary.com
    - type: github-alt
      link: https://github.com/makerdiary
    - type: twitter
      link: https://twitter.com/makerdiary
    - type: youtube
      link: https://www.youtube.com/channel/UCX4nJNlsyj9VJeQOHgOs0yg
#  disqus: 'makerdiary'
#  discourse: 'community.makerdiary.com'

# Extensions
markdown_extensions:
  - markdown.extensions.admonition
  - markdown.extensions.codehilite:
      guess_lang: false
  - markdown.extensions.def_list
  - markdown.extensions.footnotes
  - markdown.extensions.meta
  - markdown.extensions.toc:
      permalink: true
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:pymdownx.emoji.twemoji
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde


# Page tree
nav:
  - Introduction: index.md
  - Getting Started: getting-started.md
  - nRF5 SDK Tutorials:
    - Overview: nrf5-sdk/index.md
  - Zephyr RTOS Tutorials:
    - Overview: zephyr/index.md
  - Where to Buy: where-to-buy.md
  - Contributing: CONTRIBUTING.md
  - License: LICENSE.md
  
# Google Analytics
google_analytics:
  - 'UA-54344624-2'
  - auto
